site_name: Fortigate MCP Server
nav:
    - Home: index.md
    - API:
        - Advanced: advanced.md
        - Base: base.md
        - Policy: policy.md
        - Routing: routing.md
        - Security: security.md
        - Sysadmin: sysadmin.md
        - System: system.md
        - Users: users.md
        - VPN: vpn.md
plugins:
    - search
    - mkdocstrings
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: teal
          accent: purple
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: teal
          accent: lime
